
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module tempsensor(

	//////////// ARDUINO //////////
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// SW //////////
	input 		     [3:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire				CLK;
wire				reset_n;			// reset signal
	
reg				GO = 1'b0;		// The trigger for i2c communications
reg				CS = 1'b1;		// ChipSelect
reg				SDI = 1'b1;		// Slave Device Input
reg				SCLK = 1'b1;	// Our i2c clock

//=======================================================
//  Structural coding
//=======================================================

assign	reset_n = KEY[0];

i2cclock i2cclk (
		.in_clock(FPGA_CLK1_50),
		.divisor(10'd500),
		.cs(1'd1),
		.i2cclk(CLK)
);

always @(posedge CLK or negedge reset_n)
begin
	if (!reset_n)
		GO <= 0;
	else
		if (!KEY[1])
		GO <= 1;
		CS <= 1;
end

assign ARDUINO_IO[15] = CS ? CLK : SCLK;
assign ARDUINO_IO[14] = SDI;
assign ARDUINO_IO[13] = SCLK;

endmodule
